workspace = { members = [ "client","merkle_tree", "server"] }
[package]
name = "merkle_tree_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
