version: '3.7'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8000:8000"
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    depends_on:
      - server
