FROM rust:latest
WORKDIR /app
COPY . .

# Build the server binary
RUN cd /app/merkle_tree && cargo build --release
RUN cd /app/server && cargo build --release --bin server

CMD ["./target/release/server"]
